services:
    repository.speech:
        class: Doctrine\Orm\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Speech
    repository.video:
        class: Doctrine\Orm\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Video
    repository.user:
        class: Doctrine\Orm\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\ApiUser
    repository.comment:
        class: Doctrine\Orm\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Comment
    app.speech_service:
        class: AppBundle\Service\SpeechService
        arguments: ['@doctrine.orm.entity_manager', "@repository.user", "@repository.speech", "@repository.video"]
    app.video_service:
        class: AppBundle\Service\VideoService
        arguments: ['@doctrine.orm.entity_manager', "@repository.speech", "@repository.video", '%kernel.root_dir%/../web/uploads']
    app.user_service:
        class: AppBundle\Service\ApiUserService
        arguments: ['@doctrine.orm.entity_manager', "@repository.user"]
    app.comment_service:
        class: AppBundle\Service\CommentService
        arguments: ['@doctrine.orm.entity_manager', "@repository.speech", "@repository.comment", "@repository.user"]
    
    app.form.registration:
        class: AppBundle\Forms\Users\RegistrationFormType
        tags:
            - { name: form.type }
    jwt_token_authenticator:
        class: AppBundle\Security\JwtTokenAuthenticator
        autowire: true