homepage:
    path: /
    defaults: { _controller: AppBundle:Default:index}

speech_index:
    path: /speeches/
    defaults: { _controller: AppBundle:Speech:index}
    methods: [GET]

speech_get:
    path: /speeches/getChannel
    defaults: { _controller: AppBundle:Speech:getSpeech}
    methods: [GET]

speech_create:
    path: /speeches/create
    defaults: { _controller: AppBundle:Speech:create}
    methods: [POST]

video_index:
    path: /videos/
    defaults: { _controller: AppBundle:Video:index}
    methods: [GET]
video_create:
    path: /videos/create
    defaults: { _controller: AppBundle:Video:create}
    methods: [POST]
video_upload:
    path: /videos/upload
    defaults: { _controller: AppBundle:Video:upload}
    methods: [POST]

user_index:
    path: /users/
    defaults: { _controller: AppBundle:ApiUser:index}
    methods: [GET]
user_create:
    path: /users/create
    defaults: { _controller: AppBundle:ApiUser:create}
    methods: [POST]

comment_index:
    path: /comments/
    defaults: { _controller: AppBundle:Comment:index}
    methods: [GET]
comments_for_speech:
    path: /comments/getCommentsForSpeech
    defaults: { _controller: AppBundle:Comment:getCommentsForSpeech}
    methods: [POST]
comment_create:
    path: /comments/create
    defaults: { _controller: AppBundle:Comment:create}
    methods: [POST]

token_create:
    path: /token/create
    defaults: { _controller: AppBundle:Token:create}
    methods: [POST]